-- Seed data: wildlife livestream entries from explore.org
-- Source: https://explore.org/livecams

INSERT INTO streams (slug, name, description, embed_url, source_url, platform, location_name, country_code, latitude, longitude) VALUES
('decorah-eagles', 'Decorah Eagles', 'Bald eagle nest cam in Decorah, Iowa powered by explore.org', 'https://www.youtube.com/embed/IVmL3diwJuw', 'https://www.youtube.com/watch?v=IVmL3diwJuw', 'youtube', 'Decorah, Iowa, USA', 'USA', 43.3036, -91.7857),
('puffin-boulder-berm', 'Puffin Boulder Berm', 'Atlantic puffin colony boulder berm camera', 'https://www.youtube.com/embed/EqVCjIa5brY', 'https://www.youtube.com/watch?v=EqVCjIa5brY', 'youtube', 'Seal Island, Maine, USA', 'USA', 43.8956, -68.7428),
('osprey-nest-chesapeake', 'Osprey Nest', 'Osprey nest cam by Chesapeake Conservancy', 'https://www.youtube.com/embed/M9pA4F7J1Go', 'https://www.youtube.com/watch?v=M9pA4F7J1Go', 'youtube', 'Chesapeake Bay, Maryland, USA', 'USA', 38.9784, -76.4922),
('tembe-elephant-park', 'Tembe Elephant Park', 'Live camera at the Tembe Elephant Park watering hole in South Africa', 'https://www.youtube.com/embed/0P_LBKqVbfs', 'https://www.youtube.com/watch?v=0P_LBKqVbfs', 'youtube', 'Tembe Elephant Park, KwaZulu-Natal, South Africa', 'ZAF', -27.0353, 32.4266),
('african-safari', 'African Safari', 'Live safari camera from Djuma Private Game Reserve, South Africa', 'https://www.youtube.com/embed/LC-DK_22eK4', 'https://www.youtube.com/watch?v=LC-DK_22eK4', 'youtube', 'Djuma Private Game Reserve, South Africa', 'ZAF', -24.7815, 31.4478),
('outdoor-rhino-cam', 'Outdoor Rhino Cam at HESC', 'Hoedspruit Endangered Species Centre outdoor rhino camera', 'https://www.youtube.com/embed/wtylzrJvCKU', 'https://www.youtube.com/watch?v=wtylzrJvCKU', 'youtube', 'Hoedspruit, Limpopo, South Africa', 'ZAF', -24.3747, 30.9636),
('nkorho-bush-lodge', 'Nkorho Bush Lodge', 'Live camera at Nkorho Bush Lodge watering hole in Sabi Sand', 'https://www.youtube.com/embed/dIChLG4_WNs', 'https://www.youtube.com/watch?v=dIChLG4_WNs', 'youtube', 'Sabi Sand Game Reserve, South Africa', 'ZAF', -24.9000, 31.5000),
('puffin-burrow', 'Puffin Burrow', 'Atlantic puffin burrow exterior view camera', 'https://www.youtube.com/embed/5bkDe6LryCo', 'https://www.youtube.com/watch?v=5bkDe6LryCo', 'youtube', 'Seal Island, Maine, USA', 'USA', 43.8956, -68.7428),
('great-spirit-bluff-falcons', 'Great Spirit Bluff Falcons', 'Peregrine falcon nest cam at Great Spirit Bluff', 'https://www.youtube.com/embed/Vyh0NdAygyY', 'https://www.youtube.com/watch?v=Vyh0NdAygyY', 'youtube', 'Great Spirit Bluff, Minnesota, USA', 'USA', 43.7500, -91.2500),
('puffin-burrow-2', 'Puffin Burrow 2', 'Second Atlantic puffin burrow camera', 'https://www.youtube.com/embed/Ziu0WsWAukE', 'https://www.youtube.com/watch?v=Ziu0WsWAukE', 'youtube', 'Seal Island, Maine, USA', 'USA', 43.8956, -68.7428),
('osprey-nest-charlo', 'Osprey Nest 2', 'Osprey nest cam in Charlo, Montana', 'https://www.youtube.com/embed/3VVoYO-ZFPE', 'https://www.youtube.com/watch?v=3VVoYO-ZFPE', 'youtube', 'Charlo, Montana, USA', 'USA', 47.4407, -114.1682),
('underwater-reef-cam', 'Underwater Reef Cam', 'Underwater coral reef camera at Utopia Village, Honduras', 'https://www.youtube.com/embed/1zcIUk66HX4', 'https://www.youtube.com/watch?v=1zcIUk66HX4', 'youtube', 'Utopia Village, Honduras', 'HND', 16.3200, -86.5400),
('underwater-reef-dock', 'Underwater Reef Back of Dock', 'Back of dock underwater camera at Utopia Village', 'https://www.youtube.com/embed/Lv9t0hZTvz4', 'https://www.youtube.com/watch?v=Lv9t0hZTvz4', 'youtube', 'Utopia Village, Honduras', 'HND', 16.3200, -86.5400),
('puffin-loafing-ledge', 'Puffin Loafing Ledge', 'Atlantic puffin loafing ledge camera', 'https://www.youtube.com/embed/daFe_ygulPY', 'https://www.youtube.com/watch?v=daFe_ygulPY', 'youtube', 'Seal Island, Maine, USA', 'USA', 43.8956, -68.7428),
('back-channel-reef', 'Back Channel Underwater Reef', 'Utopia Village multi-cam underwater reef view', 'https://www.youtube.com/embed/nmjlQlYygB4', 'https://www.youtube.com/watch?v=nmjlQlYygB4', 'youtube', 'Utopia Village, Honduras', 'HND', 16.3200, -86.5400),
('zeabs-den', 'Zeab''s Den', 'Mission Wolf sanctuary camera — Zeab''s den', 'https://www.youtube.com/embed/1ltBSJh5qdU', 'https://www.youtube.com/watch?v=1ltBSJh5qdU', 'youtube', 'Mission Wolf, Colorado, USA', 'USA', 37.9600, -105.5500),
('boteti-river-zebra', 'Boteti River Zebra Migration', 'Live camera at the Boteti River capturing zebra migration', 'https://www.youtube.com/embed/7hKbyXxWT2k', 'https://www.youtube.com/watch?v=7hKbyXxWT2k', 'youtube', 'Boteti River, Botswana', 'BWA', -20.7000, 24.5000),
('blue-cavern-aquarium', 'Blue Cavern Aquarium', 'Aquarium of the Pacific blue cavern live cam', 'https://www.youtube.com/embed/H59B9Uoewwg', 'https://www.youtube.com/watch?v=H59B9Uoewwg', 'youtube', 'Long Beach, California, USA', 'USA', 33.7628, -118.1961),
('catalina-marine-reserve', 'USC Wrigley Catalina Marine Reserve', 'Underwater camera at USC Wrigley Marine Science Center, Catalina Island', 'https://www.youtube.com/embed/JH_NzhSsqis', 'https://www.youtube.com/watch?v=JH_NzhSsqis', 'youtube', 'Catalina Island, California, USA', 'USA', 33.4450, -118.4850),
('west-end-bald-eagle', 'West End Bald Eagle Cam', 'Bald eagle camera on the west end of Catalina Island', 'https://www.youtube.com/embed/aT1adgYSfbc', 'https://www.youtube.com/watch?v=aT1adgYSfbc', 'youtube', 'Catalina Island, California, USA', 'USA', 33.4450, -118.4850),
('castle-rock-falcons', 'Castle Rock Falcons', 'Falcon nesting camera at Castle Rock', 'https://www.youtube.com/embed/Pr9acykT_yY', 'https://www.youtube.com/watch?v=Pr9acykT_yY', 'youtube', 'Castle Rock, California, USA', 'USA', 37.3861, -122.0839),
('naledi-cat-eye', 'The Naledi', 'Naledi Cat-Eye camera in the African bush', 'https://www.youtube.com/embed/pZZst4BOpVI', 'https://www.youtube.com/watch?v=pZZst4BOpVI', 'youtube', 'Sabi Sand Game Reserve, South Africa', 'ZAF', -24.9000, 31.5000);
