export const SPECIES_EMOJI: Record<string, string> = {
  bear: "🐻",
  deer: "🦌",
  eagle: "🦅",
  owl: "🦉",
  wolf: "🐺",
  elephant: "🐘",
  lion: "🦁",
  panda: "🐼",
  penguin: "🐧",
  heron: "🪿",
  hawk: "🦅",
  fox: "🦊",
  rabbit: "🐇",
  raccoon: "🦝",
  moose: "🫎",
  bison: "🦬",
  whale: "🐋",
  dolphin: "🐬",
  turtle: "🐢",
  fish: "🐟",
  bird: "🐦",
  hummingbird: "🐦",
  osprey: "🦅",
  jellyfish: "🪼",
  koala: "🐨",
  manatee: "🦭",
  puffin: "🐦",
  falcon: "🦅",
  rhino: "🦏",
  zebra: "🦓",
  gorilla: "🦍",
  bonobo: "🐒",
  "polar bear": "🐻‍❄️",
  curlew: "🐦",
  roller: "🐦",
  "mountain goat": "🐐",
  goat: "🐐",
  horse: "🐴",
  elk: "🫎",
  flamingo: "🦩",
  lemur: "🐒",
  turkey: "🦃",
  badger: "🦡",
  oryx: "🦌",
  springbok: "🦌",
  giraffe: "🦒",
  hippo: "🦛",
  leopard: "🐆",
  cheetah: "🐆",
  hyena: "🐾",
  wildebeest: "🐃",
  panda: "🐼",
  ferret: "🦡",
  "mole-rat": "🐀",
  "naked mole-rat": "🐀",
  default: "🐾",
};

export type WildlifeCategory = "mammal" | "bird" | "aquatic";

export const WILDLIFE_CATEGORIES: Record<WildlifeCategory, { label: string; emoji: string }> = {
  mammal: { label: "Mammals", emoji: "🐾" },
  bird: { label: "Birds", emoji: "🐦" },
  aquatic: { label: "Aquatic", emoji: "🐟" },
};

export const STREAM_WILDLIFE_CATEGORY: Record<string, WildlifeCategory> = {
  "decorah-eagles": "bird",
  "puffin-boulder-berm": "bird",
  "osprey-nest-chesapeake": "bird",
  "tembe-elephant-park": "mammal",
  "african-safari": "mammal",
  "outdoor-rhino-cam": "mammal",
  "nkorho-bush-lodge": "mammal",
  "puffin-burrow": "bird",
  "great-spirit-bluff-falcons": "bird",
  "puffin-burrow-2": "bird",
  "osprey-nest-charlo": "bird",
  "underwater-reef-cam": "aquatic",
  "underwater-reef-dock": "aquatic",
  "puffin-loafing-ledge": "bird",
  "back-channel-reef": "aquatic",
  "zeabs-den": "mammal",
  "boteti-river-zebra": "mammal",
  "blue-cavern-aquarium": "aquatic",
  "catalina-marine-reserve": "aquatic",
  "west-end-bald-eagle": "bird",
  "castle-rock-falcons": "bird",
  "naledi-cat-eye": "mammal",
  "audubon-osprey-nest": "bird",
  "audubon-osprey-boat-house": "bird",
  "mendenhall-glacier-goat": "mammal",
  "bonobo-sanctuary-enclosure": "mammal",
  "bonobo-sanctuary-nursery": "mammal",
  "gorilla-forest-corridor": "mammal",
  "polar-bear-wapusk": "mammal",
  "european-roller-inside": "bird",
  "european-roller-outside": "bird",
  "homosassa-manatees": "aquatic",
  "tau-waterhole": "mammal",
  "olifants-river": "mammal",
  "black-eagles-selati": "bird",
  "rspb-osprey-nest": "bird",
  "benji-balu-bear-external": "mammal",
  "benji-balu-bear-yard": "mammal",
  "curlew-country": "bird",
  // HDOnTap cameras
  "pa-farm-country-eagles": "bird",
  "west-michigan-eagles": "bird",
  "dollywood-eagles": "bird",
  "sw-florida-river-wildlife": "bird",
  "loveland-ospreys": "bird",
  "richmond-peregrine-falcon": "bird",
  "hilton-head-eagles": "bird",
  "off-exhibit-red-wolves": "mammal",
  "greenhorn-ranch-arena": "mammal",
  "leesburg-deer-feeder": "mammal",
  "frankie-fifi-hada-horses": "mammal",
  "american-prairie-bison": "mammal",
  "montana-grasslands-bison": "mammal",
  "fishers-island-ospreys": "bird",
  "birch-aquarium-kelp": "aquatic",
  "greenhorn-dude-ranch-saloon": "mammal",
  "midpeninsula-open-space": "mammal",
  "reid-park-zoo-elephants": "mammal",
  "reid-park-zoo-flamingos": "bird",
  "reid-park-zoo-lemurs": "mammal",
  "tennessee-elk": "mammal",
  // YouTube streams
  "birds-in-the-forest-germany": "bird",
  "badgers-badgerwood": "mammal",
  "namibia-namib-desert": "mammal",
  "masai-mara-safari": "mammal",
  // Smithsonian National Zoo
  "smithsonian-panda-cam": "mammal",
  "smithsonian-lion-cam": "mammal",
  "smithsonian-elephant-cam": "mammal",
  "smithsonian-ferret-cam": "mammal",
  "smithsonian-naked-mole-rat": "mammal",
};

export const DETECTION_STALE_SECONDS = 300;
