// data.jsx — mock streams + detections for WildWatch

const SPECIES = {
  elephant:    { name: "African Elephant",  latin: "Loxodonta africana",    glyph: "E" },
  lion:        { name: "Lion",              latin: "Panthera leo",          glyph: "L" },
  zebra:       { name: "Plains Zebra",      latin: "Equus quagga",          glyph: "Z" },
  giraffe:     { name: "Reticulated Giraffe", latin: "Giraffa reticulata",  glyph: "G" },
  blackbear:   { name: "Black Bear",        latin: "Ursus americanus",      glyph: "B" },
  whitetail:   { name: "White-tailed Deer", latin: "Odocoileus virginianus",glyph: "D" },
  redfox:      { name: "Red Fox",           latin: "Vulpes vulpes",         glyph: "F" },
  arcticfox:   { name: "Arctic Fox",        latin: "Vulpes lagopus",        glyph: "A" },
  polarbear:   { name: "Polar Bear",        latin: "Ursus maritimus",       glyph: "P" },
  reefshark:   { name: "Blacktip Reef Shark", latin: "Carcharhinus melanopterus", glyph: "S" },
  manta:       { name: "Manta Ray",         latin: "Mobula alfredi",        glyph: "M" },
  toucan:      { name: "Keel-billed Toucan",latin: "Ramphastos sulfuratus", glyph: "T" },
  chickadee:   { name: "Black-capped Chickadee", latin: "Poecile atricapillus", glyph: "C" },
  cardinal:    { name: "Northern Cardinal", latin: "Cardinalis cardinalis", glyph: "R" },
  orangutan:   { name: "Bornean Orangutan", latin: "Pongo pygmaeus",        glyph: "O" },
};

const HABITAT = {
  savanna: "African Savanna",
  forest: "N. American Forest",
  tundra: "Arctic Tundra",
  reef: "Coral Reef",
  rainforest: "Rainforest",
  garden: "Backyard / Nest",
};

const STREAMS = [
  {
    id: "mara-watering-hole",
    name: "Maasai Mara Watering Hole",
    region: "Narok, Kenya",
    habitat: "savanna",
    coords: "1.5025° S, 35.1442° E",
    operator: "Kenya Wildlife Service",
    viewers: 4382,
    online: true,
    detected: "elephant",
    count: 3,
    confidence: 0.94,
    bbox: { x: 0.18, y: 0.42, w: 0.34, h: 0.36 },
    pulseAt: { x: 0.34, y: 0.6 },
    placeholder: "WATERING HOLE / DUSK LIGHT",
    featured: true,
    blurb:
      "A perennial spring fed by the Talek River, drawing herds across the dry season. Camera one of three in the Mara conservancy network — mounted in an acacia at 4.6 m, solar relay.",
  },
  {
    id: "kruger-acacia",
    name: "Kruger Acacia Plain",
    region: "Limpopo, South Africa",
    habitat: "savanna",
    coords: "23.9884° S, 31.5547° E",
    operator: "SANParks",
    viewers: 1102,
    online: true,
    detected: "zebra",
    count: 11,
    confidence: 0.89,
    bbox: { x: 0.4, y: 0.5, w: 0.45, h: 0.3 },
    pulseAt: { x: 0.62, y: 0.65 },
    placeholder: "ACACIA / HIGH SUN",
  },
  {
    id: "samburu-loop",
    name: "Samburu Reserve Loop",
    region: "Samburu, Kenya",
    habitat: "savanna",
    coords: "0.5666° N, 37.5333° E",
    operator: "Northern Rangelands Trust",
    viewers: 643,
    online: true,
    detected: "giraffe",
    count: 2,
    confidence: 0.81,
    bbox: { x: 0.35, y: 0.18, w: 0.28, h: 0.6 },
    pulseAt: { x: 0.49, y: 0.4 },
    placeholder: "OPEN PLAIN",
  },
  {
    id: "banff-pine",
    name: "Banff Pine Hollow",
    region: "Alberta, Canada",
    habitat: "forest",
    coords: "51.4968° N, 115.9281° W",
    operator: "Parks Canada",
    viewers: 891,
    online: true,
    detected: "blackbear",
    count: 1,
    confidence: 0.97,
    bbox: { x: 0.5, y: 0.45, w: 0.25, h: 0.4 },
    pulseAt: { x: 0.62, y: 0.6 },
    placeholder: "PINE FOREST FLOOR",
  },
  {
    id: "adirondack-meadow",
    name: "Adirondack East Meadow",
    region: "New York, USA",
    habitat: "forest",
    coords: "44.1135° N, 73.9243° W",
    operator: "Wildlife Conservation Society",
    viewers: 412,
    online: true,
    detected: "whitetail",
    count: 4,
    confidence: 0.91,
    bbox: { x: 0.2, y: 0.55, w: 0.3, h: 0.3 },
    pulseAt: { x: 0.32, y: 0.7 },
    placeholder: "MIXED HARDWOOD",
  },
  {
    id: "olympic-creek",
    name: "Olympic Creekside",
    region: "Washington, USA",
    habitat: "forest",
    coords: "47.7972° N, 123.6044° W",
    operator: "NPS",
    viewers: 287,
    online: true,
    detected: null,
    placeholder: "TEMPERATE RAINFOREST",
  },
  {
    id: "yukon-aurora",
    name: "Yukon Aurora Pass",
    region: "Yukon, Canada",
    habitat: "tundra",
    coords: "63.7467° N, 135.0556° W",
    operator: "Boreal Field Station",
    viewers: 1568,
    online: true,
    detected: "arcticfox",
    count: 1,
    confidence: 0.86,
    bbox: { x: 0.42, y: 0.5, w: 0.18, h: 0.28 },
    pulseAt: { x: 0.51, y: 0.62 },
    placeholder: "SNOW DRIFT / TWILIGHT",
  },
  {
    id: "svalbard-shelf",
    name: "Svalbard Ice Shelf",
    region: "Svalbard, Norway",
    habitat: "tundra",
    coords: "78.2232° N, 15.6469° E",
    operator: "Norsk Polarinstitutt",
    viewers: 2204,
    online: true,
    detected: "polarbear",
    count: 1,
    confidence: 0.93,
    bbox: { x: 0.55, y: 0.4, w: 0.3, h: 0.35 },
    pulseAt: { x: 0.7, y: 0.55 },
    placeholder: "PACK ICE",
  },
  {
    id: "gbr-lagoon",
    name: "Great Barrier Reef Lagoon",
    region: "Queensland, Australia",
    habitat: "reef",
    coords: "16.7531° S, 145.6789° E",
    operator: "AIMS",
    viewers: 3120,
    online: true,
    detected: "reefshark",
    count: 2,
    confidence: 0.88,
    bbox: { x: 0.3, y: 0.35, w: 0.4, h: 0.25 },
    pulseAt: { x: 0.5, y: 0.48 },
    placeholder: "SHALLOW LAGOON / DAYLIGHT",
  },
  {
    id: "raja-ampat",
    name: "Raja Ampat Cleaning Station",
    region: "West Papua, Indonesia",
    habitat: "reef",
    coords: "0.5897° S, 130.1031° E",
    operator: "Conservation Intl.",
    viewers: 1740,
    online: true,
    detected: "manta",
    count: 1,
    confidence: 0.95,
    bbox: { x: 0.32, y: 0.3, w: 0.4, h: 0.45 },
    pulseAt: { x: 0.52, y: 0.52 },
    placeholder: "BLUEWATER / CORAL BOMMIE",
  },
  {
    id: "borneo-canopy",
    name: "Borneo Canopy Walk",
    region: "Sabah, Malaysia",
    habitat: "rainforest",
    coords: "5.0833° N, 117.6500° E",
    operator: "WWF-Malaysia",
    viewers: 502,
    online: true,
    detected: "orangutan",
    count: 1,
    confidence: 0.79,
    bbox: { x: 0.58, y: 0.22, w: 0.22, h: 0.5 },
    pulseAt: { x: 0.69, y: 0.45 },
    placeholder: "EMERGENT CANOPY",
  },
  {
    id: "monteverde-fig",
    name: "Monteverde Fig Tree",
    region: "Puntarenas, Costa Rica",
    habitat: "rainforest",
    coords: "10.3010° N, 84.8156° W",
    operator: "Cloud Forest Trust",
    viewers: 873,
    online: true,
    detected: "toucan",
    count: 2,
    confidence: 0.84,
    bbox: { x: 0.45, y: 0.25, w: 0.18, h: 0.22 },
    pulseAt: { x: 0.54, y: 0.36 },
    placeholder: "STRANGLER FIG / MIST",
  },
  {
    id: "vermont-feeder",
    name: "Vermont Hill Feeder",
    region: "Vermont, USA",
    habitat: "garden",
    coords: "44.2601° N, 72.5754° W",
    operator: "Cornell Lab volunteer",
    viewers: 318,
    online: true,
    detected: "chickadee",
    count: 5,
    confidence: 0.92,
    bbox: { x: 0.4, y: 0.4, w: 0.22, h: 0.28 },
    pulseAt: { x: 0.51, y: 0.54 },
    placeholder: "GARDEN FEEDER",
  },
  {
    id: "tx-cardinal-nest",
    name: "Texas Cardinal Nest",
    region: "Texas, USA",
    habitat: "garden",
    coords: "30.2672° N, 97.7431° W",
    operator: "Volunteer / Hill Country",
    viewers: 96,
    online: true,
    detected: null,
    placeholder: "JUNIPER NEST CAM",
  },
  {
    id: "serengeti-kopjes",
    name: "Serengeti Kopjes",
    region: "Tanzania",
    habitat: "savanna",
    coords: "2.3333° S, 34.8333° E",
    operator: "TANAPA",
    viewers: 0,
    online: false,
    detected: null,
    placeholder: "OFFLINE — SCHEDULED MAINT.",
  },
];

const DETECTIONS = [
  { t: "16:42:08", date: "MAY 16", species: "elephant", count: 3, conf: 0.94, note: "Adult female + 2 calves" },
  { t: "16:39:51", date: "MAY 16", species: "elephant", count: 1, conf: 0.88, note: "Approach from northeast" },
  { t: "16:31:22", date: "MAY 16", species: "zebra", count: 7, conf: 0.91, note: "Crossing south to water" },
  { t: "16:18:04", date: "MAY 16", species: "giraffe", count: 1, conf: 0.83, note: "Browsing acacia" },
  { t: "15:54:37", date: "MAY 16", species: "zebra", count: 11, conf: 0.96 },
  { t: "15:22:11", date: "MAY 16", species: "lion", count: 1, conf: 0.78, note: "Sub-adult male, resting" },
  { t: "14:48:55", date: "MAY 16", species: "elephant", count: 5, conf: 0.95 },
  { t: "13:12:09", date: "MAY 16", species: "zebra", count: 4, conf: 0.87 },
  { t: "11:34:46", date: "MAY 16", species: "giraffe", count: 2, conf: 0.81 },
  { t: "09:08:17", date: "MAY 16", species: "elephant", count: 8, conf: 0.97, note: "Family group, morning visit" },
  { t: "23:41:33", date: "MAY 15", species: "lion", count: 2, conf: 0.84 },
  { t: "21:09:54", date: "MAY 15", species: "zebra", count: 15, conf: 0.93 },
];

Object.assign(window, { SPECIES, HABITAT, STREAMS, DETECTIONS });
