-- Add 21 HDOnTap cameras as jpeg-platform sources
INSERT INTO streams (slug, name, description, source_url, embed_url, platform, location_name, country_code, latitude, longitude, is_active, is_live)
VALUES
  ('pa-farm-country-eagles', 'PA Farm Country Eagles', 'Bald eagle nest in Lancaster County, Pennsylvania farm country.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb1_hdontap_lancaster-eagles_ptz-cam.stream.jpg', 'https://hdontap.com/stream/795150/pennsylvania-farm-country-bald-eagle-live-cams/', 'jpeg', 'Lancaster County, PA', 'US', 40.04, -76.31, true, true),
  ('west-michigan-eagles', 'West Michigan Eagles', 'Bald eagle nest monitored by Falconshire Raptors in western Michigan.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb6lo_falconshire_raptors-remote_ptz-avmix.jpg', 'https://hdontap.com/stream/025882/west-michigan-eagles-nest-live-cam/', 'jpeg', 'West Michigan', 'US', 43.0, -86.0, true, true),
  ('dollywood-eagles', 'Dollywood Eagles', 'American Eagle Foundation eagle aviary at Dollywood theme park.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb3_dollywood-eagles-aviary3-overlook_aef.stream.jpg', 'https://hdontap.com/stream/163290/dollywood-eagles-live-webcam-aviary-3/', 'jpeg', 'Pigeon Forge, TN', 'US', 35.79, -83.53, true, true),
  ('sw-florida-river-wildlife', 'SW Florida River Wildlife', 'Wildlife along a river in southwest Florida — eagles, wading birds, and more.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosbdvr6_eaglecountry_river1-cam.stream.jpg', 'https://hdontap.com/stream/473717/southwest-florida-river-wildlife-live-cams/', 'jpeg', 'SW Florida', 'US', 26.64, -81.87, true, true),
  ('loveland-ospreys', 'City of Loveland Ospreys', 'Osprey nest platform in Loveland, Colorado.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb3_city_of_loveland_osprey-cam.stream.jpg', 'https://hdontap.com/stream/557550/city-of-loveland-ospreys-live-cam/', 'jpeg', 'Loveland, CO', 'US', 40.40, -105.07, true, true),
  ('richmond-peregrine-falcon', 'Richmond VA Peregrine Falcon', 'Peregrine falcon nest monitored by VA Dept. of Game and Inland Fisheries.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb6lo_vdgif_falcon-cam.stream.jpg', 'https://hdontap.com/stream/397338/richmond-virginia-peregrine-falcon-live-cam/', 'jpeg', 'Richmond, VA', 'US', 37.54, -77.43, true, true),
  ('hilton-head-eagles', 'Hilton Head Island Eagles', 'Bald eagle nest on Hilton Head Island, South Carolina.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosbdvr6_hhland_eaglecam_new_large.stream.jpg', 'https://hdontap.com/stream/863293/hilton-head-island-eagles-live-webcam/', 'jpeg', 'Hilton Head, SC', 'US', 32.18, -80.75, true, true),
  ('off-exhibit-red-wolves', 'Off-Exhibit Red Wolves', 'Critically endangered red wolves at the New York Wolf Conservation Center.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb3_nywolf_off_exhibit_red_enclosure.stream.jpg', 'https://hdontap.com/stream/191785/off-exhibit-red-wolves-live-cam-wolf-center/', 'jpeg', 'South Salem, NY', 'US', 41.26, -73.53, true, true),
  ('greenhorn-ranch-arena', 'Greenhorn Ranch Horse Arena', 'Horse arena at Greenhorn Guest Ranch in the Sierra Nevada foothills.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb1_greenhorn_arena-ptz.stream.jpg', 'https://hdontap.com/stream/679471/greenhorn-ranch-live-horse-arena-cam/', 'jpeg', 'Quincy, CA', 'US', 39.94, -120.95, true, true),
  ('leesburg-deer-feeder', 'Leesburg Georgia Deer Feeder', 'Deer feeder camera in Leesburg, Georgia — deer, turkey, and other wildlife.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb6lo_kpi-deer_feeder.stream.jpg', 'https://hdontap.com/stream/203120/leesburg-georgia-live-deer-feeder-webcam/', 'jpeg', 'Leesburg, GA', 'US', 31.73, -84.17, true, true),
  ('frankie-fifi-hada-horses', 'Frankie Fifi Hada Horses', 'Horses in a pasture at VC Ranch.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb6lo_vcranch-middle_pasture.stream.jpg', 'https://hdontap.com/stream/988001/frankie-fifi-and-hada-live-horse-webcam/', 'jpeg', 'VC Ranch', 'US', 37.0, -105.0, true, true),
  ('american-prairie-bison', 'American Prairie Montana Bison', 'Bison roaming the American Prairie Reserve at White Rock, Montana.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb6lo_ap_whiterock_bison-ptz.stream.jpg', 'https://hdontap.com/stream/102875/american-prairie-montana-bison-live-cam/', 'jpeg', 'Montana Prairie', 'US', 47.80, -108.50, true, true),
  ('montana-grasslands-bison', 'Montana Grasslands Bison', 'Bison at the Enrico Education Center on American Prairie.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb6lo_ap_enrico-ptz.stream.jpg', 'https://hdontap.com/stream/429152/montana-grasslands-bison-live-webcam/', 'jpeg', 'Enrico, MT', 'US', 47.70, -108.60, true, true),
  ('fishers-island-ospreys', 'Fishers Island Ospreys', 'Osprey nest on Fishers Island, New York.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosbdvr6_hlfm_osprey-cam_ptz.stream.jpg', 'https://hdontap.com/stream/598293/fishers-island-middle-farms-ospreys-live-webcam/', 'jpeg', 'Fishers Island, NY', 'US', 41.26, -72.02, true, true),
  ('birch-aquarium-kelp', 'Birch Aquarium Kelp Forest', 'Giant kelp forest tank at the Birch Aquarium at Scripps, La Jolla.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb3_scripps_kelp_cam-ptz.stream.jpg', 'https://hdontap.com/stream/162646/birch-aquarium-kelp-forest-live-cam/', 'jpeg', 'La Jolla, CA', 'US', 32.87, -117.25, true, true),
  ('greenhorn-dude-ranch-saloon', 'Greenhorn Dude Ranch Saloon', 'Saloon view at Greenhorn Guest Ranch in the Sierra Nevada.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb1_greenhorn_saloon-ptz.stream.jpg', 'https://hdontap.com/stream/120927/greenhorn-dude-ranch-live-saloon-cam/', 'jpeg', 'Quincy, CA', 'US', 39.94, -120.95, true, true),
  ('midpeninsula-open-space', 'Midpeninsula Open Space', 'Wildlife camera in the Midpeninsula Regional Open Space District, Bay Area.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb3_mrosd_midpeninsula-ptz.stream.jpg', 'https://hdontap.com/stream/247445/midpeninsula-regional-open-space-live-webcam/', 'jpeg', 'Bay Area, CA', 'US', 37.35, -122.18, true, true),
  ('reid-park-zoo-elephants', 'Reid Park Zoo Elephants', 'African elephants at the mud pit in Reid Park Zoo, Tucson.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb3_elephant-mudpit_rpz.stream.jpg', 'https://hdontap.com/stream/259797/reid-park-zoo-elephant-mudpit-live-webcam/', 'jpeg', 'Tucson, AZ', 'US', 32.21, -110.92, true, true),
  ('reid-park-zoo-flamingos', 'Reid Park Zoo Flamingos', 'Flamingos at Reid Park Zoo, Tucson.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb1_flamingo_rpz.stream.jpg', 'https://hdontap.com/stream/269273/reid-park-zoo-flamingos-live-webcam/', 'jpeg', 'Tucson, AZ', 'US', 32.21, -110.92, true, true),
  ('reid-park-zoo-lemurs', 'Reid Park Zoo Lemurs', 'Ring-tailed lemurs at Reid Park Zoo, Tucson.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb3_lemur_rpz.stream.jpg', 'https://hdontap.com/stream/103166/reid-park-zoo-lemurs-live-webcam/', 'jpeg', 'Tucson, AZ', 'US', 32.21, -110.92, true, true),
  ('tennessee-elk', 'Tennessee Elk', 'Elk cam managed by the Tennessee Wildlife Resources Agency.', 'https://storage.hdontap.com/wowza_stream_thumbnails/snapshot_hosb3_tennessee-elk-cam_twra.stream.jpg', 'https://hdontap.com/stream/359514/tennessee-elk-live-webcam/', 'jpeg', 'Tennessee', 'US', 36.40, -84.80, true, true)
ON CONFLICT (slug) DO NOTHING;
